[package]
name = "dicey"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2"
pest_derive = "2"
num_enum = "0.5"
enum_dispatch = "0.3"
anyhow = "1"
fastrand = "1"
log = "0.4"
num = "0.4"
num-traits = "0.2"
smartstring = "1"

[dev-dependencies]
simple_logger = "4"
once_cell = "1"
